<script lang="ts">
	import { reveal } from '../actions/reveal';

	// Optimized derivatives generated by scripts/generate-logo-derivatives.mjs
	// (`pnpm logos`); the raw assets in $lib/assets are up to 2000x2000.
	const logos = {
		invoicelab: '/images/logos/invoicelab.webp',
		mc2finance: '/images/logos/mc2finance.webp',
		dolpin: '/images/logos/dolpin.svg',
		dosier: '/images/logos/dosier.webp',
		qdacademy: '/images/logos/qdacademy.webp',
		signupcash: '/images/logos/signupcash.webp',
		devsonket: '/images/logos/devsonket.webp',
		yieldfinder: '/images/logos/yieldfinder.ico',
		raisolo: '/images/logos/raisolo.webp'
	};

	interface CareerEntry {
		name: string;
		years: string;
		url: string;
		logo: string;
		description: string;
	}

	// Newest first.
	const career: CareerEntry[] = [
		{
			name: 'invoice lab',
			years: '2025 - present',
			url: 'https://staging.invoicelab.live/',
			logo: logos.invoicelab,
			description: 'AI-powered invoice management. Intelligent, customizable, and professional.'
		},
		{
			name: 'raisolo',
			years: '2025 - 2026',
			url: 'https://raisolo.com/',
			logo: logos.raisolo,
			description:
				'An AI-driven product built to automate research, insights, content workflows, and orchestrate personal hivemind'
		},
		{
			name: 'yieldfinder.ai',
			years: '2025',
			url: 'https://yieldfinder.ai/',
			logo: logos.yieldfinder,
			description: 'Intelligent, AI-Powered DeFi Yield using AI Agents & MCP Server'
		},
		{
			name: 'mc² finance',
			years: '2023 - 2026',
			url: 'https://www.mc2.fi/',
			logo: logos.mc2finance,
			description: 'The First Regulated DeFi ETPs. Deliver 15% SOL, 10% USD, and 7% CHF Yields.'
		},
		{
			name: 'dolpin',
			years: '2022 - 2023',
			url: 'https://www.dolpin.io/',
			logo: logos.dolpin,
			description: 'A decentralized & encrypted storage layer built with IPFS / Filecoin.'
		},
		{
			name: 'dosier',
			years: '2022 - 2023',
			url: 'https://www.dosier.ai/',
			logo: logos.dosier,
			description:
				'Decentralized Content Delivery, harnessing the power of Data DAOs and zk-SNARK transactions. Backed by LonghashX & ProtocolLabs'
		},
		{
			name: 'quickdesk academy',
			years: '2021 - 2022',
			url: 'https://theqdacademy.com/',
			logo: logos.qdacademy,
			description: 'Professional training and skill development academy'
		}
	];

	const projects: CareerEntry[] = [
		{
			name: 'devsonket',
			years: '2018 - present',
			url: 'https://devsonket.com/',
			logo: logos.devsonket,
			description: 'Open Source developer community and technical resource platform'
		},
		{
			name: 'signup.cash',
			years: '2020 - 2021',
			url: 'https://github.com/signupcash',
			logo: logos.signupcash,
			description: 'Non-Custodial Wallet & SLP/NFT storage for Bitcoin Cash'
		}
	];
</script>

<!-- Career: a vertical timeline, newest first. -->
<section
	id="work"
	class="cv-auto mx-auto flex min-h-screen w-full max-w-[900px] flex-1 scroll-mt-24 flex-col items-center justify-center px-8 py-24"
>
	<h2 class="mb-4 text-center text-sm font-medium tracking-widest lowercase text-muted" use:reveal>
		career timeline
	</h2>
	<p class="mb-16 max-w-xl text-center text-sm text-muted" use:reveal>
		companies and teams i've worked with over the years
	</p>

	<ol class="w-full">
		{#each career as entry, i (entry.name)}
			<li class="grid grid-cols-[52px_1fr] gap-3 sm:grid-cols-[88px_1fr] sm:gap-6" use:reveal>
				<!-- Year rail -->
				<div
					class="whitespace-pre-line pt-1 text-right text-xs font-medium leading-relaxed text-muted tabular-nums sm:text-sm"
				>
					{entry.years.replace(' - ', ' –\n')}
				</div>

				<!-- Node + content. The whole block is the outbound link. -->
				<div class="relative min-w-0 border-l border-line-soft {i === career.length - 1 ? 'pb-2' : 'pb-10'}">
					<span
						class="absolute -left-[5px] top-2 h-2.5 w-2.5 rounded-full bg-accent"
						aria-hidden="true"
					></span>
					<a
						href={entry.url}
						target="_blank"
						rel="noopener noreferrer"
						class="group ml-5 flex items-start gap-4 rounded-2xl border border-transparent p-2 -m-2 transition-all duration-300 hover:border-line-soft hover:bg-card sm:ml-8 sm:gap-5 sm:p-4 sm:-m-4"
					>
						<div
							class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border border-line-soft bg-card p-2 sm:h-16 sm:w-16 sm:p-2.5"
						>
							<img
								src={entry.logo}
								alt="{entry.name} logo"
								width="64"
								height="64"
								loading="lazy"
								decoding="async"
								class="h-full w-full object-contain"
							/>
						</div>
						<div class="min-w-0">
							<h3
								class="flex items-center gap-1.5 text-lg font-bold tracking-tight transition-colors group-hover:text-accent"
							>
								{entry.name}
								<svg
									class="h-3.5 w-3.5 shrink-0 text-muted transition-all duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:text-accent"
									fill="none"
									stroke="currentColor"
									stroke-width="2"
									viewBox="0 0 24 24"
									aria-hidden="true"
								>
									<path stroke-linecap="round" stroke-linejoin="round" d="M7 17L17 7M7 7h10v10"></path>
								</svg>
							</h3>
							<p class="mt-1.5 text-base leading-relaxed text-muted">
								{entry.description}
							</p>
						</div>
					</a>
				</div>
			</li>
		{/each}
	</ol>
</section>

<!-- Projects: self-started and open-source work, as a simple card grid. -->
<section
	id="projects"
	class="cv-auto mx-auto flex w-full max-w-[900px] flex-1 scroll-mt-24 flex-col items-center px-8 py-24"
>
	<h2 class="mb-4 text-center text-sm font-medium tracking-widest lowercase text-muted" use:reveal>
		projects
	</h2>
	<p class="mb-16 max-w-xl text-center text-sm text-muted" use:reveal>
		things i've built and maintain outside of work
	</p>

	<div class="grid w-full gap-6 sm:grid-cols-2">
		{#each projects as entry (entry.name)}
			<a
				href={entry.url}
				target="_blank"
				rel="noopener noreferrer"
				class="group flex flex-col items-center rounded-2xl border border-line-soft bg-card px-8 py-10 text-center transition-all duration-300 hover:-translate-y-1 hover:border-accent/40 hover:shadow-2xl"
				use:reveal
			>
				<div
					class="mb-6 flex h-20 w-20 items-center justify-center rounded-2xl border border-line-soft bg-card p-3 transition-transform duration-300 group-hover:scale-110"
				>
					<img
						src={entry.logo}
						alt="{entry.name} logo"
						width="80"
						height="80"
						loading="lazy"
						decoding="async"
						class="h-full w-full object-contain"
					/>
				</div>
				<h3
					class="flex items-center gap-1.5 text-xl font-bold tracking-tight transition-colors group-hover:text-accent"
				>
					{entry.name}
					<svg
						class="h-4 w-4 shrink-0 text-muted transition-all duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:text-accent"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						viewBox="0 0 24 24"
						aria-hidden="true"
					>
						<path stroke-linecap="round" stroke-linejoin="round" d="M7 17L17 7M7 7h10v10"></path>
					</svg>
				</h3>
				<p class="mt-1 text-sm font-medium text-muted tabular-nums">
					{entry.years}
				</p>
				<p class="mt-3 text-base leading-relaxed text-muted">
					{entry.description}
				</p>
			</a>
		{/each}
	</div>
</section>
